; Script generated by the HM NIS Edit Script Wizard.

ManifestDPIAware true

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "UtauV"
!define PRODUCT_PUBLISHER "asoqwer"
!define PRODUCT_WEB_SITE "https://github.com/emeraldsingers/UtauV"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; Build-specific paths are supplied by the release workflow. Keep defaults so
; the script remains usable locally and by older workflows.
!ifndef BUILD_DIR
  !define BUILD_DIR "bin\win-${ARCH}"
!endif
!ifndef OUTPUT_NAME
  !define OUTPUT_NAME "UtauV-win-${ARCH}.exe"
!endif

; MUI 1.8 compatible ------
!include "MUI2.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "OpenUtau\Assets\open-utau.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\UtauV.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "French"
!insertmacro MUI_LANGUAGE "German"
!insertmacro MUI_LANGUAGE "Japanese"
!insertmacro MUI_LANGUAGE "Korean"
!insertmacro MUI_LANGUAGE "Russian"
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "${OUTPUT_NAME}"
InstallDir "$PROGRAMFILES64\UtauV"
ShowInstDetails show
ShowUnInstDetails show

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File /r "${BUILD_DIR}\*"
SectionEnd

Section -AdditionalIcons
  CreateShortCut "$SMPROGRAMS\UtauV.lnk" "$INSTDIR\UtauV.exe"
  CreateShortCut "$DESKTOP\UtauV.lnk" "$INSTDIR\UtauV.exe"
SectionEnd

Section -Post
  ;leave a mark that the program was installed
  FileOpen $9 "$INSTDIR\installed.txt" w
  FileWrite $9 "yes"
  FileClose $9

  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\UtauV.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"

  WriteRegStr HKCR ".ustx" "" "UtauVFile"
  WriteRegStr HKCR "UtauVFile" "" "UtauV Sequence File"
  WriteRegStr HKCR "UtauVFile\DefaultIcon" "" "$INSTDIR\UtauV.exe"
  WriteRegStr HKCR "UtauVFile\shell\open\command" "" '"$INSTDIR\UtauV.exe" "%1"'
SectionEnd

Section "VC Redist"
  SetOutPath "$INSTDIR"
  File "vc_redist.${ARCH}.exe"
  ExecWait "$INSTDIR\vc_redist.${ARCH}.exe"
  Delete "$INSTDIR\vc_redist.${ARCH}.exe"
SectionEnd

Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer."
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\uninst.exe"
  RMDir /r "$INSTDIR\Data"
  RMDir /r "$INSTDIR\bin"
  Delete "$INSTDIR\*"
  RMDir "$INSTDIR"

  Delete "$SMPROGRAMS\UtauV.lnk"
  Delete "$DESKTOP\UtauV.lnk"

  DeleteRegKey HKCR ".ustx"
  DeleteRegKey HKCR "UtauVFile"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  SetAutoClose true
SectionEnd
