//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenUtau.Core.Vogen.Data {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VogenRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VogenRes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vogen.Data.VogenRes", typeof(VogenRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] f0_man {
            get {
                object obj = ResourceManager.GetObject("f0_man", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] f0_yue {
            get {
                object obj = ResourceManager.GetObject("f0_yue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] g2p_man {
            get {
                object obj = ResourceManager.GetObject("g2p_man", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] g2p_yue {
            get {
                object obj = ResourceManager.GetObject("g2p_yue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] po_man {
            get {
                object obj = ResourceManager.GetObject("po_man", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] po_yue {
            get {
                object obj = ResourceManager.GetObject("po_yue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ch,yue,yue-nn,yue-wz
        ///㐀,jau,jau,jau
        ///㐁,dou,du,dou
        ///㐂,cat,cat,cat
        ///㐃,zim,zim,zim
        ///㐄,kwaa,kwaa,kwaa
        ///㐅,ng,ng,ng
        ///㐆,ji,ji,ji
        ///㐇,gau,gau,gau
        ///㐈,jap,jap,jap
        ///㐉,ding,ding,ding
        ///㐊,si,si,si
        ///㐋,tou,tu,tou
        ///㐌,ji,taa,taa
        ///㐍,zaau,zaau,zaau
        ///㐎,man,man,man
        ///㐏,ng,ng,ng
        ///㐐,nou,nu,nou
        ///㐑,dung,dung,dung
        ///㐒,ziu,ziu,ziu
        ///㐓,ho,ho,ho
        ///㐔,hang,hang,hang
        ///㐕,jau,jau,jau
        ///㐖,kit,jit,jit
        ///㐗,lou,lu,lou
        ///㐘,mai,mai,mai
        ///㐙,dau,dau,dau
        ///㐚,ng,ng,ng
        ///㐛,jau,jau,jau
        ///㐜,sau,cau,cau
        ///㐝,keoi,kyu,kyu
        ///㐞,kei,ki,ki
        ///㐟,fei,fi,fi
        ///㐠,jyu,jyu,jyu
        ///㐡,no,no,no
        ///㐢,fau,fau,fau
        ///㐣,fu,fu,fu
        ///㐤,da [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string yue {
            get {
                return ResourceManager.GetString("yue", resourceCulture);
            }
        }
    }
}
